import { StyleSheet } from "react-native";

export default {
  dark: StyleSheet.create({
    container: { flex: 1, backgroundColor: "#000", padding: 16 },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    title: { fontSize: 28, fontWeight: "700", color: "#fff" },
    uploadBtn: {
      backgroundColor: "#B983FF",
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 20,
    },
    uploadText: { color: "#fff", fontWeight: "600" },
    checkboxContainer: { marginBottom: 20 },
    checkboxRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#1E1E1E",
      borderRadius: 10,
      padding: 12,
      marginBottom: 10,
    },
    label: { color: "#fff", fontSize: 16, marginLeft: 10 },
    input: {
      backgroundColor: "#1E1E1E",
      color: "#fff",
      borderRadius: 10,
      padding: 16,
      fontSize: 16,
      marginBottom: 12,
    },
    processBtn: {
      backgroundColor: "#B983FF",
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 30,
    },
    processText: { color: "#fff", fontWeight: "600" },
    divider: { height: 1, backgroundColor: "#333", marginVertical: 20 },
    chatTitle: { color: "#fff", fontSize: 20, fontWeight: "600", marginBottom: 12 },
    chatBtn: {
      backgroundColor: "#B983FF",
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 20,
    },
    chatText: { color: "#fff", fontWeight: "600" },
  }),
  light: StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f3ead9ff", padding: 16 },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    title: { fontSize: 28, fontWeight: "700", color: "#000" },
    uploadBtn: {
      backgroundColor: "#B983FF",
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 20,
    },
    uploadText: { color: "#fff", fontWeight: "600" },
    checkboxContainer: { marginBottom: 20 },
    checkboxRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#eee",
      borderRadius: 10,
      padding: 12,
      marginBottom: 10,
    },
    label: { color: "#000", fontSize: 16, marginLeft: 10 },
    input: {
      backgroundColor: "#eee",
      color: "#000",
      borderRadius: 10,
      padding: 16,
      fontSize: 16,
      marginBottom: 12,
    },
    processBtn: {
      backgroundColor: "#B983FF",
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 30,
    },
    processText: { color: "#fff", fontWeight: "600" },
    divider: { height: 1, backgroundColor: "#ccc", marginVertical: 20 },
    chatTitle: { color: "#000", fontSize: 20, fontWeight: "600", marginBottom: 12 },
    chatBtn: {
      backgroundColor: "#B983FF",
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      marginBottom: 20,
    },
    chatText: { color: "#fff", fontWeight: "600" },
  }),
};
